# Generated by Django 5.1.1 on 2024-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='user_images/default.png', upload_to='profile_images/'),
        ),
    ]
