# Generated by Django 5.1.1 on 2024-10-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_user_img_profiletesting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletesting',
            old_name='user',
            new_name='user_in_profile_testing_model',
        ),
    ]
