# Generated by Django 5.1.1 on 2024-10-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_user_profiletesting_user_in_profile_testing_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletesting',
            old_name='user_in_profile_testing_model',
            new_name='user',
        ),
    ]
