# Generated by Django 5.1.1 on 2024-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_rename_user_in_profile_testing_model_profiletesting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletesting',
            old_name='user',
            new_name='author',
        ),
    ]
