# Generated by Django 5.1.1 on 2024-10-10 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_user_profiletesting_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(blank=True, max_length=200)),
                ('post_like', models.CharField(blank=True, max_length=200)),
                ('post_comment', models.CharField(blank=True, max_length=200)),
                ('post_title', models.CharField(blank=True, max_length=200)),
                ('post_description', models.TextField(blank=True)),
                ('post_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
