# Generated by Django 5.1.1 on 2024-10-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_post_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletesting',
            old_name='author',
            new_name='user',
        ),
    ]
