# Generated by Django 5.1.1 on 2024-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletesting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profiletesting',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profiletesting',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiletesting',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
