# Generated by Django 5.1.1 on 2024-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_post_post_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
