# Generated by Django 5.1.1 on 2024-10-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_post_liked_by_alter_post_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
