# Generated by Django 5.1.1 on 2024-10-13 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_post_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.ManyToManyField(related_name='blog_post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
