# Generated by Django 5.1.1 on 2024-10-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_remove_post_post_like_remove_post_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
    ]
