# Generated by Django 5.1.1 on 2024-10-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_remove_post_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
