# Generated by Django 5.1.1 on 2024-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_alter_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
