# Generated by Django 5.1.1 on 2024-10-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_profile_profile_update_time_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_update_time',
        ),
    ]
